// This file was generated by counterfeiter
package fake_command_runner

import (
	"sync"

	"github.com/pivotal-cf-experimental/kafka-example-service-adapter/adapter"
)

type FakeCommandRunner struct {
	RunStub        func(name string, arg ...string) ([]byte, []byte, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		name string
		arg  []string
	}
	runReturns struct {
		result1 []byte
		result2 []byte
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCommandRunner) Run(name string, arg ...string) ([]byte, []byte, error) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		name string
		arg  []string
	}{name, arg})
	fake.recordInvocation("Run", []interface{}{name, arg})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(name, arg...)
	} else {
		return fake.runReturns.result1, fake.runReturns.result2, fake.runReturns.result3
	}
}

func (fake *FakeCommandRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeCommandRunner) RunArgsForCall(i int) (string, []string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].name, fake.runArgsForCall[i].arg
}

func (fake *FakeCommandRunner) RunReturns(result1 []byte, result2 []byte, result3 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 []byte
		result2 []byte
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCommandRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCommandRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ adapter.CommandRunner = new(FakeCommandRunner)
